### ISSUE TITLE
Concrete models and on the fly declaration 

### ISSUE THREAD

**Issue by billxinli** [twg/devour#14] opened 2016-05-05 21:51 UTC
Restangular style allows for arbitrary "models" be used in the various calls.

Currently this library requires explicit model definition. Curious about the pros and cons of each.

Relates to #6 and #11

**Comment by derek-watson** [comment] 2016-05-05 22:42
That's the same question I'm trying to ask in #6. I don't see any reason for it as it stands, it only adds impediments to using the library.

**Comment by billxinli** [comment] 2016-05-05 22:46
The library contains code that allows model-less requests to be built out:

https://github.com/twg/devour/blob/master/index.js#L179

So we can extend on that.

My personal belief is that there should only be one source of truth for the model, and that should be the server side, since it gets messy if we introduce validators or complex model specific domain logic, then we may need to keep both sides in sync.

**Comment by derek-watson** [comment] 2016-05-07 18:48
Should we build on the code that allows model-less requests, or just get rid of the model definitions? I don't see any use for them.

**Comment by Emerson** [comment] 2016-05-09 16:48
I consider this a duplicate of #6 and I think there is an elegant approach to this that offers people the best of both worlds.

@billxinli – I agree in principle about the source of truth, but not everyone has control over their API's and I think it's important to provide mechanisms for the client side to be smarter if the need arises.

**Closed by Emerson** 2016-05-09 16:48 UTC
